spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080