spring:
  application:
    name: projet-integrador-2
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto-integrador-2
    username: user-projeto-integrador-2
    password: ut0M5cenlZqxpm8
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080