CREATE TABLE USERS (
                       ID INTEGER NOT NULL,
                       NAME VARCHAR(100) NOT NULL,
                       USERNAME VARCHAR(100) NOT NULL,
                       PASSWORD VARCHAR(100) NOT NULL,
                       ACTIVE BOOLEAN  NOT NULL DEFAULT TRUE,
                       CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       UPDATED_AT TIMESTAMP
);

CREATE SEQUENCE SQ_USERS_ID START 1 INCREMENT 1 OWNED BY USERS.ID;

ALTER TABLE USERS ADD CONSTRAINT PK_ID_USERS PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT UK_USERNAME_USERS UNIQUE (USERNAME);

CREATE TABLE ROLES (
                       ID INTEGER NOT NULL,
                       NAME VARCHAR(100) NOT NULL,
                       DESCRIPTION VARCHAR(100) NOT NULL,
                       CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       UPDATED_AT TIMESTAMP
);

CREATE SEQUENCE SQ_ROLES_ID START 1 INCREMENT 1 OWNED BY ROLES.ID;

ALTER TABLE ROLES ADD CONSTRAINT PK_ID_ROLES PRIMARY KEY (ID);
ALTER TABLE ROLES ADD CONSTRAINT UK_NAME_ROLES UNIQUE (NAME);

CREATE TABLE USERS_ROLES (
                             USER_ID INTEGER NOT NULL,
                             ROLE_ID INTEGER NOT NULL
);

ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_USERS_ID FOREIGN KEY (USER_ID) REFERENCES users(ID);
ALTER TABLE USERS_ROLES ADD CONSTRAINT FK_ROLES_ID FOREIGN KEY (ROLE_ID) REFERENCES roles(ID);

--senha-root
INSERT INTO USERS
(ID, NAME, USERNAME, PASSWORD)
VALUES
    (nextval('SQ_USERS_ID'), 'Root', 'root', '$2a$12$PvIzsPwdJSJvgAFDfM6WPu5nToCKuTPRijh4fX6OjwJIsEMLrAh8m');

--senha-admin
INSERT INTO USERS
(ID, NAME, USERNAME, PASSWORD)
VALUES
    (nextval('SQ_USERS_ID'), 'Administrador', 'admin', '$2a$12$IOOSbHD9umswOg2LOHl86uKcwKWnLfBmLdKgqGLF1GRaJaff8j3W.');

--senha-user
INSERT INTO USERS
(ID, NAME, USERNAME, PASSWORD)
VALUES
    (nextval('SQ_USERS_ID'), 'Usuario', 'user', '$2a$12$MEoC5oOz11Df4DYqOjL/QeutqOthlcWVe3y7vkRku2gwvUU6lyZmO');

--123
INSERT INTO USERS
(ID, NAME, USERNAME, PASSWORD)
VALUES
    (nextval('SQ_USERS_ID'), 'Luiz Henrique', 'luiz-canassa', '$2a$12$..RtCNlwCrNSqlggBd1TbuIDjDHHUHmEuOSWimY8Muqh5OWJNfQwW');

INSERT INTO ROLES
(ID, NAME, DESCRIPTION)
VALUES
    (nextval('SQ_ROLES_ID'), 'ROLE_ROOT', 'Root');

INSERT INTO ROLES
(ID, NAME, DESCRIPTION)
VALUES
    (nextval('SQ_ROLES_ID'), 'ROLE_ADMIN', 'Administrador');

INSERT INTO ROLES
(ID, NAME, DESCRIPTION)
VALUES
    (nextval('SQ_ROLES_ID'), 'ROLE_USER', 'Usuário');


INSERT INTO USERS_ROLES
(USER_ID, ROLE_ID)
VALUES
    (1,1);

INSERT INTO USERS_ROLES
(USER_ID, ROLE_ID)
VALUES
    (2,2);

INSERT INTO USERS_ROLES
(USER_ID, ROLE_ID)
VALUES
    (3, 3);

INSERT INTO USERS_ROLES
(USER_ID, ROLE_ID)
VALUES
    (4, 3);